name: Drupal setup workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Validate composer
        run: composer validate --strict
      - name: composer cache dir
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock')}}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drupal-build
          path: ./

      - name: Deploy artifacts
        uses: actions/download-artifact@v3
        with:
          name: drupal-build
      - name: Initialise git repo
        run: |
          git init
          ls -la