name: Drupal setup workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Validate composer
        run: composer validate --strict
      - name: composer cache dir
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock')}}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drupal-build
          path: ./
      - name: set permission
        run: chmod -R 777 /home/runner/work/gh_drupal/gh_drupal/.git
      - name: Deploy artifacts
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: drupal-build
      - name: Initialise git repo
        run: |
          ls -la
          git config --global user.email ${{ secrets.EMAIL_ID }}
          git config --global user.name ${{ secrets.NAME }}
          git checkout -b ${{ github.ref_name }}-build
          git add .
          git commit -m "Deployed artifacts."
          git push origin ${{ github.ref_name }}-build